## Circleci version
version: 2

## Machine specific variable
jobs:
  build:
    machine:
       image: ubuntu-2004:202101-01

## Build crc-libvirt-driver
    working_directory: ~/work
    steps:
    - checkout
    - run:
       name: Build driver binary
       command: make CONTAINER_RUNTIME="docker"
    - store_artifacts:
       path: ~/work/crc-driver-libvirt-centos8
       destination: crc-driver-libvirt
    - store_artifacts:
       path: ~/work/crc-driver-libvirt-ubuntu20.04
       destination: crc-driver-libvirt-ubuntu20.04

